### ISSUE TITLE
Consensus on Chapter references?

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#10]
I would like to propose a convention to how we reference other chapters, in this book.

Currently, most of the references are of the form `Chapter *cha:syntax*`, which renders to 'Chapter [3](link to the chapter)'. 

I'd like to add the following - let's actually type out the name of the chapter. So, let's standardize the references as `Chapter *cha:syntax*: Syntax in a Nutshell`. The LaTeX-style relative link to the chapter number will protect us from chapter re-ordering operations. 
It's true that typing out the name of the chapter makes it harder to rename a chapter. But I think that the added cognitive clarity for specifying the title is worth the additional effort during the rare renaming operations (where one can just do a global search for the old name, '`*cha:syntax*: Syntax in a Nutshell'`, etc).
Thoughts?

(Possibly put the chapter title in italics?).

**Edit:** Turns out that `*cha:syntax*` is incorrect markup, it should be `*syntax*` for reference, without the 'cha:'.

**Comment by Ducasse** [comment]
It is ok now we should do it for all the references so this is some work.

**Comment by dmitrizagidulin** [comment]
@Ducasse I'm happy to go through and update all the existing references. Are you ok with this convention, in principle, though?

**Comment by Ducasse** [comment]
yes then can you try to see if we use *Syntax in a nutshell>cha:syntax* would work so that the link is Syntax In a Nutshell.
Probably the best would be 
Chapter *cha:Syntax* (*Syntax in a Nutshell>cha:syntax*)
so that we get 
Chapter 3 (Syntax in a Nutshell) in latex and url in Latex.
Can you experiment and tell us?

**Comment by dmitrizagidulin** [comment]
Ok, ran some tests. The good news is that I understand why the `*cha:basic*` ref was not working, in the Collections chapter (https://github.com/SquareBracketAssociates/UpdatedPharoByExample/pull/8#discussion-diff-27666444R717 ).
The syntax is: `@cha:basic` for the anchor in the chapter, and then `Chapter *basic*` when referring to it. (Minus the `cha:`).
Also, the reference is only going to be rendered correctly if you compile the whole book, but not if you just compile the chapter. (I knew this part already).
(By the way, I see that compiling the book yields a whole-book PDF, and compiling a single chapter yields a chapter PDF and a chapter HTML. But is there a whole-book HTML artifact?)

The bad news is that `Chapter *chapterSyntaxNutshell* (*Syntax in a Nutshell>chapterSyntaxNutshell*)` renders to 'Chapter [4](correct link) ([4](correct link))' in PDF (with the correctly-linked 4), and `Chapter \ref{chapterSyntaxNutshell} (\ref{chapterSyntaxNutshell})` in LaTeX. So, no luck making the chapter name part of the link. (Seems like an un-implemented feature in Pillar).

I think our options are:
1. Try and use in-line raw LaTeX reference? (something like `{{{latex: ... }}}`, I don't actually know what the correct tex syntax for it is).
2. Try and implement the correct behavior (`*Syntax in a Nutshell>chapterSyntaxNutshell*`) in Pillar. (Out of my league, for the moment :) ).
3. For the moment, compromise on having the linked chapter number, and a plain text (or italic) chapter name. (So, we'd say `Chapter *cha:chapterSyntaxNutshell*: Syntax in a Nutshell`).

What do you think?

**Comment by Ducasse** [comment]
Not yet for the full html book but it will come with Table of contents and the rest.
And yes you are right this was a stupid remark of mine. 
For the moment we should do it as 3.

**Comment by dmitrizagidulin** [comment]
Thanks Stef! I opened issue #12, to go through and fix all the current references, using option 3.
Closing this current issue.

**Comment by Ducasse** [comment]
super!
