### ISSUE TITLE
Nautilus

### ISSUE THREAD

**Issue by jecisc** [SquareBracketAssociates/UpdatedPharoByExample#101]
We could explain that Nautilus is the system browser in the section System Browser in PharoTour.
That wasn't understood by a someone which read UPBE.

**Comment by kilon** [comment]
fixed with this commit

https://github.com/SquareBracketAssociates/UpdatedPharoByExample/commit/ba2f9ee60a22a78c817028442050a9eda193a769

**Comment by jecisc** [comment]
Thank you :) @kilon

**Comment by kilon** [comment]
my pleasure :)
