### ISSUE TITLE
Collections - get rid of Collections hierarchy stats

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#109]
The second paragraph of the Collections chapter has several statistics about the class hierarchy, such as:
```
These 56 classes respond to 982 messages and define a total of 1609 methods!
```
The counts have obviously changed from Pharo 1.1 to Pharo 4 (and so those numbers are incorrect). But more importantly, they are likely to change with each Pharo version, and book maintainers will have to re-count those classes and edit that paragraph.
Given that the stats are information-free (readers do not care that there are 1609 methods), we should remove this paragraph.

**Comment by jecisc** [comment]
We can also create a script that will generate these stat.
For example in an intern ship report about Pillar I had a script that generated some stat when I compiled my pillar document. This looked in the image I used to compile my report.

**Comment by jecisc** [comment]
So we can write something like:

    [[[eval=true
        stream nextPutAll: 'In Pharo, the abstract class ==Collection== has ';
     	    	nextPutAll: Collection allSubclasses size asString;
      		nextPutAll:
     				' subclasses, and the abstract class ==Stream== has ';
    	 	nextPutAll: Stream allSubclasses size asString;
     		nextPutAll: 'blablabla'.
     ]]]

**Comment by dmitrizagidulin** [comment]
@jecisc Wait, so, that'll evaluate in the context of the image, and print text to the LaTeX stream, basically? That's awesome! Good to know.

So, on the one hand, I'm glad that functionality exists. And, putting in a sample script (a non-executable one) to count the classes, messages and methods would be somewhat useful (for readers to look at and understand how to count these things). Although if that was the purpose, the Collection chapter is not where it belongs -- it should be in the Pharo Object Model chapter, or in Reflection.

My main objection with this paragraph that provides the count, is that's it's completely information-free. It's just arbitrary numbers. Readers do not care about the class or method count, at all. So why clutter the chapter?

**Comment by jecisc** [comment]
We use that for example in the Pillar chapter to generate the list of parameters we can use on a Pillar configuration.
See: https://github.com/SquareBracketAssociates/EnterprisePharo/blob/master/PillarChap/Pillar.pillar#L501

**Comment by dmitrizagidulin** [comment]
@jecisc that's so cool!! (Hey, that reminds me -- does `language=smalltalk` have to be lowercase? Or does `=Smalltalk` also work?)

**Comment by jecisc** [comment]
I will have to check that but if that have to be lowercase I think I'll change that to allow both.

**Comment by jecisc** [comment]
I checked and you can write "Smalltalk" as "smalltalk" as "SmallTalk" :)

**Comment by dmitrizagidulin** [comment]
Excellent, ok :)

Back to the original discussion, though -- will you object if I remove the stats sentence?

**Comment by jecisc** [comment]
Merged. Thank you!
