### ISSUE TITLE
Streams - Question about ReadWriteStream support

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#112]
In the Streams chapter, in the `Streams vs. Collections` section:

```
The main problem with ==WriteStream== and ==ReadWriteStream== is that they only
support arrays and strings in Pharo. This is currently being changed by the
development of a new library named Nile, but for now if you try to stream over
another kind of collection, you will get an error:
```
Is that still the case? Or do we have support for collections, in Pharo 4?

**Comment by Ducasse** [comment]
Nile will not be used.
We will probably use Xtreams.
I do not know for the collections so I would not mention it.

**Comment by jecisc** [comment]
All the SequenciableCollection and Files seems to be able to use it.
If you look for the writeStream or readStream methods on the finder you find that: 
http://puu.sh/iG0PC/3e48184408.png

**Comment by dmitrizagidulin** [comment]
Thanks. I'll remove that paragraph.
