### ISSUE TITLE
Collections - Re-do Collection hierarchy image

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#113]
The Collection hierarchy has changed by Pharo 4. (Dictionary is now a subclass of HashedCollection and not of Set, etc).
We need to re-do Figure 11.1 (Some of the key collection classes in Pharo.):

![Collection hierarchy](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/raw/master/Collections/figures/CollectionHierarchy.png)

**Comment by Ducasse** [comment]
I redid it. I will upload it.

**Comment by dmitrizagidulin** [comment]
Oh! Nice! Closing this issue, then. :)  (looks like the new image is all set)

**Comment by Ducasse** [comment]
I commited. Have a look

**Comment by dmitrizagidulin** [comment]
Looks great! Thanks!
