### ISSUE TITLE
Playground > exploreIt menu tiem does not exist

### ISSUE THREAD

**Issue by bencoman** [SquareBracketAssociates/UpdatedPharoByExample#114]
I am starting to review UPBE, fixing in my fork as I go.   PharoTour page 10 says...
> Close the inspector. Type the expression Object in a playground and this time explore it (CMD-I, that is, the uppercase i, or CMD-SHIFT-i).

but in build 40618 there is no such "explore it" menu item.  It should probably be changed to "inspect it" ?

**Comment by DamienCassou** [comment]
You should remove everything related to "Explore it" as we now only have "Inspect it" and it is probably already covered by the chapter

**Comment by bencoman** [comment]
On Tue, Aug 18, 2015 at 4:20 PM, Damien Cassou <notifications@github.com>
wrote:

> You should remove everything related to "Explore it" as we now only have
> "Inspect it" and it is probably already covered by the chapter
>
>
>
Cool. Will do.
cheers -ben

**Comment by kilon** [comment]
fixed with https://github.com/SquareBracketAssociates/UpdatedPharoByExample/commit/dfe7729347f0172bbcdcd796fdcd7b87498f8ab5
