### ISSUE TITLE
list of class browser icons

### ISSUE THREAD

**Issue by zio-pietro** [SquareBracketAssociates/UpdatedPharoByExample#120]
class browser - the main tool - in it's four panes uses a set of small icons for additional information about items. I thing it should be somewhere (maybe Appendix X.Y) complete list of these icons and theirs meanings. Some of them I decode myself, but IMHO the list is missing.

**Comment by DamienCassou** [comment]
I agree. Please do it and we will fill the holes.

**Comment by zio-pietro** [comment]
Il 28/09/2015 09:14, Damien Cassou ha scritto:
>
> I agree. Please do it and we will fill the holes.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/SquareBracketAssociates/UpdatedPharoByExample/issues/120#issuecomment-143657761>.
>
Hi Damien,

thanks a lot, you made my day ;) I'm smalltalk and Pharo newbie, my 
whole experience with this language is two weeks long.
So I really can't do it yet, I'm sorry. Maybe later.
Just after some small talk with Kilos I started corrector reading of 
UPBE. I'm dancin' as fast as I can ;)

Ragards
Pietro

**Comment by kilon** [comment]
icon description has been added with the relevant image 

https://github.com/SquareBracketAssociates/UpdatedPharoByExample/commit/7f475f1c24630cfd5c1a1be4458675f8f179dc3e
