### ISSUE TITLE
Pillar markup in the middle of a chapter

### ISSUE THREAD

**Issue by gozes** [SquareBracketAssociates/UpdatedPharoByExample#121]
on chapter 1 from page 15 to 19 all the text is Pillar markdown and the screenshots are missing

**Comment by cdlm** [comment]
which version ? on CI the preface looks OK and hasn't been rebuilt since 2 weeks

**Comment by gozes** [comment]
not sure because I got the link from kilon on IRC

**Comment by gozes** [comment]
look at https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/book-result/UpdatedPharoByExample.pdf on page 21 to page 28 and you will see what I mean.

**Comment by cdlm** [comment]
Oh ok. Section 2.9, page 14 and following. On page 21 I just see `[[[ lang= Smalltalk shout ^ self asUppercase,’!’ ]]]` at the bottom, but the figures are there.

@jecisc is this using bleeding edge Pillar?

**Comment by jecisc** [comment]
It use the stable version but we didn't check all the books when we changed the parser. It is possible that something is not right on the new parser. I opened an Issue on Pillar's github.

**Comment by DamienCassou** [comment]
I fixed all problems I found. Please open a new issue if there are more.
