### ISSUE TITLE
SeasideByExample - Revise/update

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#126]
Revise Seaside chapter for Pharo 4, latest Seaside. Do not use one-click image, that's sadly based on 1.4.

**Comment by kilon** [comment]
frankly I vote for the complete removal of that chapter for several reasons

a) Its not a begineer orientated chapter as is the focus of this book
b) its not general purpose as is the focus of this book
c) far harder to keep this updated constantly which again is the focus of this book, since not many of us use seaside 
d) It already has its own book and its own documentation which can easily refer to. 

So I vote for the complete removal of this chapter so we have one less thing to worry about updating.

**Comment by dmitrizagidulin** [comment]
You bring up good points. I'm of mixed opinion, regarding this chapter.

On the one hand, you're right, it is not a beginner-oriented chapter. In fact, I was going to propose adding an `Interacting with the Web` chapter right before it, which would cover really simple use cases on how to consume and serve HTTP using Zinc Components. (Since fetching things via a REST API is such a common developer use case). (And also possibly mention Zinc-REST and Teapot). I was planning to wait until I finished revising other chapters, before adding that one. But, since you raise the topic of relevance to beginners, I thought I'd mention it.

But on the other hand, I can think of several reasons to keep this chapter:

1. Seaside is still a pretty amazing framework, and a valuable feature of the Pharo ecosystem. It could be argued that Seaside's popularity in the early 2000s helped bring a surge of interest and developer eyeballs to Squeak and later Pharo. And, I would argue that many Pharo developers still use it. (Though it would be interesting to see actual numbers, of course). 
2. Though Seaside does already have its own book (in the form of [Dynamic Web Development with Seaside](http://book.seaside.st/book) and the [Gemstone GLASS Tutorial](http://seaside.gemtalksystems.com/tutorial.html)), I would argue that this chapter is the best hope for updated documentation, for developers interested in Seaside. The Dynamic Web Dev book is very out of date, and does not exist in a source control repo like UPBE. Same with the GLASS tutorial.

So, I could see it either way. I mean, ideally, I would love to find the original source code for Dynamic Web Development (maybe @Ducasse or Lukas Renggli or David Shaffer have it?), and move that to a Pillar book repo of its own. Or, failing that, extract this Seaside chapter into its own book. (And replace it with a more basic `Interacting with the Web` chapter).

**Comment by Ducasse** [comment]
Please keep this chapter. It is stable and this is nice to get started with seaside in one chapter and seaside is stable. It also shows right in the beginner guide that we can do sexy web app with Pharo. 
We will migrate the seaside book to pillar but too busy.

**Comment by DamienCassou** [comment]
I agree with @Ducasse, the Seaside chapter is a nice one to have in a beginners book. The Dynamic Web Development book has started to be ported to Pillar. But we lack time and people to help.

**Comment by kilon** [comment]
then its decided, Seaside chapter will remain but I am afraid I cannot assist with its update since web development is something that I don't need or do or find interesting :)

**Comment by dmitrizagidulin** [comment]
@DamienCassou wait, what's this? The Dynamic Web Dev book is being ported, and needs help? Is there a repo you can point me to? 
This is exciting! :)

**Comment by DamienCassou** [comment]
@dmitrizagidulin as far as I know, @jbrichau started taking care of it. He was waiting for some Pillar features before going further. I think most of the requested features have been implemented now.

**Comment by dmitrizagidulin** [comment]
@DamienCassou encourage him to throw whatever source code he has up into a repo, and people can help him convert it into Pillar markup (just like we did with PBE). :)

**Comment by kilon** [comment]
Yeap I can help there too, converting is fairly easy :)

**Comment by jbrichau** [comment]
As @DamienCassou mentions, I intended to do this a year ago but I hit quite a number of limitations in Pillar which made converting the book to a Pillar format not so easy as it seems. There are quite a number of Pier extensions that the book uses, but nothing is impossible. In addition, Pillar has included a number features that were absolutely necessary (such as cross-page links). 

Right now, I seriously lack time to pick the task up again and I gave all source data we got from Lukas to @philippeback who volunteered to pick this up. I'm willing to help out, but I cannot commit to this task right now as Seaside itself (and its website) is something I want to take care of first.

Any new format that can be maintained for the future has my support and I _will_ update the text with information from the current Seaside version (something which is impossible/useless to do right now as maintaining the current sources is uncertain). But, as I said, converting is just not something I can spend my time on right now.... 

Send me a PM if you want the links to the sources from Lukas to figure out how to get started.

**Comment by jbrichau** [comment]
Btw, here is the repo I got started on: https://github.com/SquareBracketAssociates/DynamicWebDevelopmentWithSeaside

**Comment by dmitrizagidulin** [comment]
@jbrichau - Thanks Johan, I sent you an email about the book source code.

@Ducasse and @DamienCassou - I *still* think we have these chapters backwards. Consider:
In Pharo By Example, which is a *beginner* level book, we interrupt our discussion of the actual Pharo language and launch into a description of a particular high-level  web development framework (Seaside).

But in [Enterprise Pharo: A Web Perspective](https://github.com/SquareBracketAssociates/EnterprisePharo), which *is a book about web frameworks*, we don't talk about the Seaside framework, but instead do talk about very beginner-level topics like Zinc Client, which answers the basic question of "how do I retrieve some text from a web url using Pharo". 

Why do we feel that beginners should learn how to create heavy weight web applications before they can even do an HTTP GET with Pharo? Or before they can serve the simplest HTTP API call?

Ask yourself this, too - does *any* other beginner programming language book do this? Do Ruby books stop for a full blown discussion on Ruby on Rails? No, at best they mention how to retrieve stuff with an HTTP client. Do Python books that are teaching people the language introduce the Django web framework? No. And so on.

(On a similar subject, why do we feel that simple File I/O is an advanced topic (which we leave to [Chapter 3 of Deep Into Pharo](http://pharobooks.gforge.inria.fr/PharoByExampleTwo-Eng/latest/PBE2.pdf#chapter.3) but, again, full blown web app development is beginner?)
(And why are Regular Expressions included in PBE, when they're also featured as a chapter in Deep Into Pharo?)

I strongly believe that we need to move the Zinc Client and File I/O chapters *into* UPBE, and the Seaside and Regular Expression chapters out of it. In order of importance:

1. Move the Zinc HTTP Client chapter from Enterprise to UPBE. And move Files with FileSystem from DeepIntoPharo into UBPE. Currently, a reader who finishes PBE has a programming language with no way to get data in or out of it! They can't do the most basic operations -- read some lines from a data file, or from a web API.

2. Remove the RegularExpression chapter from UPBE. This chapter already exists in Deep Into Pharo.

3. Move the Seaside chapter to Enterprise Pharo: A Web Perspective. Since that book is, specifically, about web frameworks!

**Comment by kilon** [comment]
Regular Expressions should NOT be moved out they are part of the Pharo distribution and very important tool for any coder.

**Comment by dmitrizagidulin** [comment]
The question is not whether Regular Expressions are important or not. :) The question is - which book should they be included in. My point here is, since the RegEx chapter already exists in the 2nd book, why also duplicate it in the first book.

**Comment by dmitrizagidulin** [comment]
Moving the 'Where to put the Seaside chapter' discussion to issue #133, since that's a separate issue.
Since, regardless of where we put it, it still needs to be revised and updated.

**Comment by kilon** [comment]
hmm good point, just keep a reference that points to Deep Into Pharo and remove regex.

Although I dont know if the readers hate us if we keep bouncing them between multiple books :D

**Comment by dmitrizagidulin** [comment]
> Please keep this chapter. It is stable and this is nice to get started with seaside in one chapter and  seaside is stable.
Neither Seaside nor this chapter are in any way stable, btw :)  It's going to need a *lot* of updating.

**Comment by jbrichau** [comment]
@dmitrizagidulin I disagree: Seaside is very stable. It has only evolved slightly over the past 5 years to keep it up to date. In anticipation of the rework of the Seaside book, I can help updating this chapter though. So unless this is going to be removed, I will update it.

**Comment by Ducasse** [comment]
Hi johan 
this is my point. I imagine that there are just the registration or something like that that changes

**Comment by jbrichau** [comment]
I see there has already been some work done. Nice!
I will see where I can contribute and send a pull request.

**Comment by dmitrizagidulin** [comment]
Thanks, @jbrichau!

**Comment by nicolaihess** [comment]
closing this issue, as the seaside chapter is (at least the first half) updated/fixed.
