### ISSUE TITLE
Collections - Mention substring-related methods in the Strings section

### ISSUE THREAD

**Issue by zio-pietro** [SquareBracketAssociates/UpdatedPharoByExample#127]
Substrings are so uncommon operations that they aren't even mentioned in Basic Classes-Strings nor in Collections chapter. (Voluntary ironic)
Some methods as allButFirst:  or last: should be mentioned with 'all of them you can find in String class - use System Browser'.

Just my 5 cents.

**Comment by dmitrizagidulin** [comment]
@zio-pietro Thanks for the heads-up. Yes, we should mention a couple of substring-related methods.
Please feel free to add those mentions yourself (in the Collections chapter), and submit a pull request. :)

**Comment by zio-pietro** [comment]
Hi Dmitri,
just started write something.
btw. thanks for opinion about note/quote difference :)

**Comment by zio-pietro** [comment]
Done, pull request submited, waiting for merge

**Comment by dmitrizagidulin** [comment]
Implemented in @zio-pietro's PR #132 (thanks!).
Closing.

**Comment by kilon** [comment]
great job guys
