### ISSUE TITLE
Create a mock Environment chapter

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#13]
Since we have references to Chapter 6: Environment elsewhere in the book (like in https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/PharoTour/PharoTour.pillar#L613 ), and that chapter hasn't been ported yet from the original book, we should create an empty/mock Environment chapter and give it a chapter id anchor. So that the links would at least work.

**Comment by Ducasse** [comment]
Yes good idea.

**Comment by dmitrizagidulin** [comment]
PR merged, closing.
