### ISSUE TITLE
Using or not using LaTeX snippets in Pillar sources?

### ISSUE THREAD

**Issue by zio-pietro** [SquareBracketAssociates/UpdatedPharoByExample#130]
A small question about symbol --> and in essence about using or not LaTeX (and HTML) snippets in Pillar/Pier sources.
See result at http://imgbin.org/index.php?page=image&id=27000

**Comment by dmitrizagidulin** [comment]
What does the actual pillar markup that generates that code block, in the image, look like?

**Comment by zio-pietro** [comment]
In code block I don't know, but I'm happy with it, looks well.

**Comment by dmitrizagidulin** [comment]
I'm not sure I understand this issue, or what you're asking.

**Comment by zio-pietro** [comment]
In code blocks arrow is rendered as LaTeX math symbol \to{} and IMHO looks wery well.
I thing it's job of \begin{script} \end{script} environment. In paragraph text Pillar's ==-\\->== is rendered
as -- > (minus minus greather), double minus then LaTeX change to middle long hyphen. Using instead LaTex snippet {{{latex:$\to$}}}, rendering is visually identical as in code block.
My question: what symbol we can use in paragraph text? And I vote for LaTeX snippet, offering to change it in whole book, if approved.

**Comment by kilon** [comment]
Latex should not be used unless absolutely necessary so it makes easy for people not knowing Latex to contribute. I already fixed that with Pillar so you dont need to use Latex. Latex is an optional tool for Pillar and is required only for PDF generation which is optional too and mainly handles by our automatic builds. So Latex must not be used . If there is a need its far better to make feature request for Pillar.
