### ISSUE TITLE
to Pillar maintainers

### ISSUE THREAD

**Issue by zio-pietro** [SquareBracketAssociates/UpdatedPharoByExample#131]
Nothing to worry about, now when we have compille1chapter scripts (and work well, tnx Damien), it's
only my curiosity:
with ./compile1ChapterInPDF.sh Preface/Preface.pillar I got this result http://imgbin.org/index.php?page=image&id=27001 (a bit of Preface/Preface.tex)
contrary to http://imgbin.org/index.php?page=image&id=27002 (the same bit of book-result/output.tex),  obtained with ./pillar export --to=latex Preface/Preface.pillar . Note mix of LaTeX $ $ inline math with HTML entity and the same entity also in code block. Exported with --to=latex parameter.

Typesetting of output.tex with pillarPostExport.sh then fails on
./output.tex:9: Undefined control sequence.
l.9 \definecolor{codebox}{HTML}{e4e4e4}

Once more, it isn't important now, as we have compille1chapter scripts, so can be adjusted as item 3350 on todo list ;)

**Comment by DamienCassou** [comment]
Thanks for the feedback. However, the parameter to the `--to` option is important:

- when you write `--to="LaTeX by chapter"`, you get the configuration specified in [pillar.conf](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/e247f31b931b0e036520ee11104860c92d67c5e2/pillar.conf#L16)

- when you write `--to=latex`, you get the default LaTeX configuration, including the default LaTeX template which is not good at all I agree. Please open an issue on the Pillar issue tracker about that.

I don't see the problem with the book itself. As a result I'm closing the issue. Please reopen if you want to add information.
