### ISSUE TITLE
Should we start removing pictures ?

### ISSUE THREAD

**Issue by kilon** [SquareBracketAssociates/UpdatedPharoByExample#138]
Pictures are all nice and good but they are a pain to maintain and become even more quickly outdated than text. So I vote to start removing pictures that don't serve a substantial usage. For example do the reader need a picture of inspector that shows him how the inspector looks when he can simply open the inspector for himself in the pharo image ? I think not. Pictures should be used only to explain GUI elements, for example like the image we have that explains the columns of System Browser. 

In any case I want to rid many of the pictures included in PBE and instead use more descriptive text but of course I want your thought on this as well.

**Comment by Ducasse** [comment]
before doing that we could give a chance to the script of stefan eggermont. 
Because we have all the power to script and do automatic screen capture. I just do not have the energy to do it now.

**Comment by Ducasse** [comment]
And often you read book in a bus or something like that and you do not have a computer at hand.

**Comment by kilon** [comment]
The problem is that even with script , and this is not the first time this is brought up , it will be a lot of extra work. It will be a lot of effort to make every single image into a script to generate the image and people will still have to maintain the script if something is changed in the content of the tutorial. It will also introduce another barrier for newcomers to contribute to documentation. 

I still think it does not worth the effort and I think having less images in the book beats even having images generated by automated scripts it terms of maintenance and ease of use. 

I think we must keep things as simple as possible and make it super easy for people to contribute.

I also dont understand your second reply, the issue of images is unrelated to whether you read UPBE as a book or as an electronic format. And yes nowdays almost everyone has a smartphone so everyone has a computer at hand , literally, and yes I prefer a real book. Removing those image will help use slim down the book considerably because they take a lot of space , especially with Pillar being unable to place them in a page without leaving big gaps.

**Comment by Ducasse** [comment]
A book describing IDE without pictures is strange. Please do the following. Make a list of pictures that we should produce and I will produce them. 
This is a book for NEWCOMERS, the ide is intimidating. So seeing what you get is important. 
I'm sorry but I read books in metro. airplanes, bus and I do not run pharo on my smartphone and I do not open my machines to click on a menu when I read a book. So please pay attention that we spent a lot of time in this book and while some parts were boring et tedious because they were too oriented towards interaction, putting screenshots is IMPORTANT.

**Comment by kilon** [comment]
ok the screenshots remain, closed
