### ISSUE TITLE
PharoTour - update 'operating.png' to 4.0

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#14]
1. Update `PharoTour/figures/operating.png` to reflect Pharo 4.0 (currently shows a Workspace instead of Playground, etc).
2. Uncomment the reference to it on https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/PharoTour/PharoTour.pillar#L168

**Comment by Ducasse** [comment]
cool

**Comment by dmitrizagidulin** [comment]
This issue is fixed by PR #111. Closing.
