### ISSUE TITLE
Reflection - Re-do 'Introspection' section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#142]
The `Introspection` section ([line #34](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/Reflection/Reflection.pier#L34)) currently depends on the old Inspector behavior (the ability to change instance variables from within the inspector).

Since current Pharo inspectors do not allow you to change variables directly, this example won't work. (Not to mention, the screenshot is outdated).

This section needs to be redone.

**Comment by nicolaihess** [comment]
I think this is fixed now.
