### ISSUE TITLE
Reflection - Fix 'Classes, method dictionaries and methods' section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#144]
The `Classes, method dictionaries and methods` needs to be redone. ([line 327](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/Reflection/Reflection.pier#L327))

It currently uses the obsolete Explorer view. At very least, this needs screenshots updated and re-written with the new Inspector in mind.

**Comment by nicolaihess** [comment]
screenshots fixed

**Comment by Ducasse** [comment]
Tx nicolai
I'm back on this book.

**Comment by nicolaihess** [comment]
fixed
