### ISSUE TITLE
Reflection - Fix 'Browsing environments' section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#145]
The `Browsing environments` section currently uses the `Refactoring Browser` for its examples.

The RB (and the menu shortcuts (`Refactoring > Subclasses with`, etc)) no longer exists in Pharo.
This section needs to be redone (if it's still relevant), with updated screenshots.

**Comment by dmitrizagidulin** [comment]
In the `Method contexts` section, the `Integer>>factorial` script uses `thisContext explore.`
(Also, I'm not quite clear on why that's referred to as "the poor man's debugger".) 

Redo this section, update screenshots.

**Comment by nicolaihess** [comment]
Removed all references to OBBrowser/Refactoring Browser functions that are not yet available in Nautilus.
(and updated the screenshots)

**Comment by Ducasse** [comment]
super!
