### ISSUE TITLE
Reflection - Fix 'Method contexts' / explore reference.

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#147]
In the `Method contexts` section, the `Integer>>factorial` script uses `thisContext explore.`
(Also, I'm not quite clear on why that's referred to as "the poor man's debugger".) 

Redo this section, update screenshots.

**Comment by nicolaihess** [comment]
I changed this to thisContext inspect and updated some other references.

The "poor mans debugger" is about having an inspector of a Context, can act like a debugger, you can see and change variable values, inspect the stack or walk the senders chain. (I added this description too).
