### ISSUE TITLE
How to translate?

### ISSUE THREAD

**Issue by momoewang** [SquareBracketAssociates/UpdatedPharoByExample#158]
I want to translate this book to Chinese, but pillar exports messy code. How to configure for changing local language?

**Comment by Ducasse** [comment]
Can you explain what you are doing? What do you mean by messy code.
Pillar does not handle different language. Pillar accepts UTF-8 and then the latex template should manage the different glyph and format encodings.

**Comment by momoewang** [comment]
I try again. Thank you.

**Comment by lolisa** [comment]
@momoewang I'm interested in helping the translation progress.

**Comment by SergeStinckwich** [comment]
Hi guys ! That would be great to have a chinese edition of Pharo By Example book.
Do you know if there is any chinese Smalltalk mailing-list. I know chinesesqueak@googlegroups.com and squeak-cn@lists.squeakfoundation.org but apparently these lists are dead.
Thank you.

**Comment by lolisa** [comment]
If you guys use QQ, I just made a smalltalk group, 202659332.

**Comment by Ducasse** [comment]
Put your translation on github :) and also translate the Updated Pharo by Example version. 
We should release it soon.

**Comment by SergeStinckwich** [comment]
I dunno what is QQ. Usually we use traditional mailing-lists or Google groups.
Try to build a Pharo mailing-list somewhere.
Thank you.

**Comment by kilon** [comment]
Just an advice , you can save ton of work using automatic translation, I once translated a whole chapter from French to English , using google translate , without doing any translation myself 

Not sure how good its translation to chinese is but it does not hurt to try

https://translate.google.com/
