### ISSUE TITLE
PharoTour - add 'save image under new name' example

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#16]
In the 'Saving, quitting and restarting a Pharo session' section, around [line 229](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/PharoTour/PharoTour.pillar#L229), we say `Alternatively, you may save the image under a new name, as we just did.`

But we haven't actually done that, previously. It's probably referring to a section that was once there, or something?
We should demonstrate how to do that.

**Comment by Ducasse** [comment]
No just remove ", as we just did."

**Comment by dmitrizagidulin** [comment]
Removed. Closing.
