### ISSUE TITLE
Link to completed PDF Is a 404

### ISSUE THREAD

**Issue by samis** [SquareBracketAssociates/UpdatedPharoByExample#163]
The URL for the completed PDF linked to in the README.md results in the server giving a 404 / 'File not found' error.  It might be a good idea to either ensure that the PDF is created or that the link is removed from the README.

**Comment by cdlm** [comment]
Might be because the build process is different since the migration to the new LaTeX class, and jenkins didn't get updated because the setting has to be changed manually…

**Comment by Uko** [comment]
:+1:

**Comment by cdlm** [comment]
Tweaked the build config on Jenkins; the individual chapters were compiled but not the whole book (yet another pet peeve of mine about jenkins: the build setup is not versioned in the repo like Travis…)

[Build 282](https://ci.inria.fr/pharo-contribution/view/Books/job/UpdatedPharoByExample/282/) should build the whole thing; please reopen if not.
