### ISSUE TITLE
PharoTour - mention Pharo launcher

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#17]
In the Installing Pharo section, we talk about how once you have multiple VMs and images installed, you have to be careful and either drag&drop them onto the VM, or invoke specific images on the command line.

Might this be a good opportunity to mention the Pharo Launcher project? (If so, we should probably link to it from the Download Pharo page..)

**Comment by Ducasse** [comment]
Yes. We can point to the launcher. People should use it because it is cool.
And we can add a link to the Deep into Pharo chapter on ZeroConf.
