### ISSUE TITLE
first application initialize method and unfortunate image placement

### ISSUE THREAD

**Issue by nicolaihess** [SquareBracketAssociates/UpdatedPharoByExample#175]
The \#initialize method for LOCell is the only code example which has line numbers.
This is impractically for copy and pasting the example. 
And the image (Figure "The newly-created method initialize") is placed within the code example. You could easliy miss the last code line

**Comment by Ducasse** [comment]
Yes we should remove them.

**Comment by nicolaihess** [comment]
I now removed the line numbering from this method. Other methods still use line numbering but those methods are explicit repeated for a line-by-line explanation.
The placement is still unfortunate, because the last code line is on the following page, below the figure.
But I don't think we can control this.
