### ISSUE TITLE
PharoTour - clarify keeping VM and .sources in separate dir

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#18]
In the 'Pharo components' section, we say:
```
The ''.sources'' file and the VM can be read-only, and can be shared between
different users. All of these files can be placed in the same directory, but it
is also possible to put the Virtual Machine and sources file in separate
directory where everyone has access to them.
```
But if you store the VM and `.sources` in separate directories, how do you tell the VM where to look for the sources? I assume there's some kind of commandline parameter? And if so, we should explain / provide an example. (And, if not, we should remove that sentence).

**Comment by Ducasse** [comment]
I do not know. ask on the mailing-list because I forgot after all these years. I'm not sure that there is a lookup.

**Comment by dmitrizagidulin** [comment]
Sure thing. Asking.
