### ISSUE TITLE
Mistake in first application example.

### ISSUE THREAD

**Issue by TheSecretSquad** [SquareBracketAssociates/UpdatedPharoByExample#187]
There is a mistake in the Lights Out game example in the following location:

Chapter 3.9 - A first application - Let's try our code

> This turns out to be behavior that we inherit from `SimpleSwitch-
> Morph`. We can fix this simply by overriding `mouseMove:` to do nothing:
> `LOGame >> mouseMove: anEvent`

In the above quote, `LOGame >> mouseMove: anEvent`, should be `LOCell >> mouseMove: anEvent`, as `LOCell` inherits from `SimpleSwitchMorph`.

**Comment by nicolaihess** [comment]
Thank you,
I wil fix it.

**Comment by TheSecretSquad** [comment]
@nicolaihess You're welcome. Thank you!
