### ISSUE TITLE
References to Nautilus

### ISSUE THREAD

**Issue by nounder** [SquareBracketAssociates/UpdatedPharoByExample#218]
Along with release of [Pharo 7.0](https://pharo.org/news/pharo7.0-released) Nautilus browser is no more. It is replaced by Calypso.

Because of this, all examples using Nautilus, do not work.

**Comment by dalanicolai** [comment]
For people reading this. The name of the new system browser object seems to be `ClyFullBrowser`, so that this name can be used instead of `Nautilus` (in most cases I guess).

**Comment by dalanicolai** [comment]
Can you please create a `pharo7` branch? I am reading the book now and I'm willing to contribute updates and corrections for pharo 7. But there should exist a pharo7 branch for that.

**Comment by Ducasse** [comment]
Thanks dalanicolai. If you want to contribute please use Pharo by Example 8. https://github.com/SquareBracketAssociates/PharoByExample80
We do fully separated project for new versions because the effort is massive. 
This is a book for Pharo by Example 50 as written on the cover.

**Comment by Ducasse** [comment]
We are planning a release of the new book for march 2020.
