### ISSUE TITLE
BUG: No Windows support in Pharo or Glamorous Toolkit ... You HAVE to support Windows

### ISSUE THREAD

**Issue by richlysakowski** [SquareBracketAssociates/UpdatedPharoByExample#227]
Not supporting Windows OS is a BUG.   Enough said.

**Comment by jecisc** [comment]
Hi,
I don't know for GToolkit but Pharo is working on windows.
If you cannot use Pharo on windows, there is probably a bug and in that case we need a description of this bug: https://github.com/pharo-project/pharo/issues
