### ISSUE TITLE
FirstApplication - complete the 'Creating a new Package' section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#25]
In the FirstApplication chapter, in the 'Creating new Package' section, it says:

    ... Now we will see how to create packages, categories and classes.

    Type the name of the new package (we will use PBE-LightsOut) in the dialog box
    and click ""accept"" (or just press the return key);

However, we don't explain what the dialog box is (and certainly don't have an example/screenshot); that's the first time the dialog box is mentioned.

So, we should probably finish this section and explain what we're referring to.

**Comment by Ducasse** [comment]
Categories is not part of the vocabulary anymore, it is protocol for methods.
we should say select add Package menu and enter the package name. No need to discuss a dialog.

**Comment by dmitrizagidulin** [comment]
Nice, ok!

**Comment by dmitrizagidulin** [comment]
Ok, see PR #29 for the fix (which turned out to be slightly more involved than removing the paragraph).

**Comment by dmitrizagidulin** [comment]
Merged, closing issue.
