### ISSUE TITLE
FirstApplication - Revise for Pharo 4.0

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#27]
Go through the chapter, make sure the code still works on 4.0, and that the concepts that we're talking about still apply (ie, the class comments pane has moved, etc).

Also, this chapter is lacking in screenshots (though that should probably go into its own issue).

**Comment by Ducasse** [comment]
thanks!

**Comment by jecisc** [comment]
done in https://github.com/SquareBracketAssociates/UpdatedPharoByExample/pull/78

Need review

**Comment by dmitrizagidulin** [comment]
@jecisc Nice work on #78. Reviewed your changes, the chapter looks great. Closing this issue.
