### ISSUE TITLE
Add a section on Spotter

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#31]
Spotter is one of the fantastic new features integrated into Pharo 4.
We need a section with examples & screenshots (either in the Environment chapter, or somewhere appropriate).

http://www.humane-assessment.com/blog/introducing-gtspotter

**Comment by dmitrizagidulin** [comment]
We have a `Using Spotlight` section towards the end of PharoTour chapter. This is probably where the Spotter intro should go, if not earlier.

**Comment by kilon** [comment]
I replaced the spotlight section in the Quick Pharo Tour chapter with Spotter documentation 

https://github.com/SquareBracketAssociates/UpdatedPharoByExample/commit/82296c12e7987286f6a00ceb1f801cc019acd0b0
