### ISSUE TITLE
FirstApplication - Clarify 'variables are really constants' paragraph

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#32]
In the 'Inspecting an Object' section of FirstApplication, there is a paragraph:

```
Let's look at this ==initialize== method. The line ==\| sampleCell width height n \|==
declares 4 temporary variables. They are called temporary variables because
their scope and lifetime are limited to this method. Temporary variables with
explanatory names are helpful in making code more readable. Smalltalk has no
special syntax to distinguish constants and variables, and in fact all four of
these "variables" are really constants. Lines 4\-7 define these constants.
```
The `all four of these "variables" are really constants` line is confusing to a new user. 
What is it supposed to mean? We need to either explain further, or remove that sentence.

**Comment by Ducasse** [comment]
you can say 
set the values of these variables.

**Comment by dmitrizagidulin** [comment]
@Ducasse is it ok to remove the sentence `Smalltalk has no
special syntax to distinguish constants and variables, and in fact all four of
these "variables" are really constants.`?

**Comment by Ducasse** [comment]
Yes this is over precise and wrong!

**Comment by dmitrizagidulin** [comment]
Fix committed, closing
