### ISSUE TITLE
FirstApplication - Update/verify SmalltalkHub workflow section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#36]
In FirstApplication, in the `SmalltalkHub: a Github for Pharo` [section](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/16f073c30af26fa884ae9ea5096c511d88502f85/FirstApplication/FirstApplication.pier#L606):

1. Verify that the SmalltalkHub join and register project workflow is still as described

2. Change the line `To add a SmalltalkHub repository select ==HTTP==.` to use the `SmalltalkHub` repository type.

3. The section on loading packages is slightly confusing (since the reader is in the context of already being in a repository browser):
    ```
    To load a package into your image, you must first select a particular version.
    You can do this in the repository browser, which you can open using the button
    or the right-click menu. Once you have selected a version, you can load it onto
    your image.

    Open the ==PBE-LightsOut== repository you have just saved.
    ```
    And also ends abruptly after "Open this repository". Maybe we should add a separate "Loading packages from SmalltalkHub" subsection? Mention briefly how to load the newest version (and how the browser shows which monticello package you've loaded already via underline, etc)?

**Comment by kilon** [comment]
Yeap definetly and Configurations also need to be mentioned like , load and loadDevelpment as should also Gofer commands. Just the basics to get the game started and also point to more detailed chapters.
