### ISSUE TITLE
Travis CI job is erroring out

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#4]
https://travis-ci.org/SquareBracketAssociates/UpdatedPharoByExample/builds/55576432

The book CI job is erroring out and failing for mysterious IP/DNS-related reasons:

```
Err http://us.archive.ubuntu.com/ubuntu/ precise-updates/main libc6-dev amd64 2.15-0ubuntu10.10

404 Not Found [IP: 2001:67c:1562::17 80]
```

**Comment by DamienCassou** [comment]
Fixed, thanks
