### ISSUE TITLE
PharoObjectModel - Revise for Pharo 4.0

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#40]
(From what I understand, @Ducasse is working on this one?)

**Comment by dmitrizagidulin** [comment]
Just to double-check, is it safe to revise this chapter, or is @Ducasse currently working on it?

**Comment by Ducasse** [comment]
yes because I got stuck there.
So I appreciate that you look at it and it will help me to make progress

**Comment by dmitrizagidulin** [comment]
@Ducasse thanks! I'll take a look at it.

**Comment by dmitrizagidulin** [comment]
@Ducasse - I've finished the LaTeX to Pillar conversion of the Pharo Object Model chapter, and took a first pass at updating it for Pharo 4. Aside from a couple of items of clarification (for which I'll open separate issues), I think it's ready to go.
Take a glance through it, see if there are any more glaring things that need to be updated.

**Comment by dmitrizagidulin** [comment]
@Ducasse - Any thoughts?

**Comment by Ducasse** [comment]
Excellent! I will add it.

**Comment by Ducasse** [comment]
to my mailing-list

**Comment by dmitrizagidulin** [comment]
Closing (will open specific issues on the Object Model chapter separately)
