### ISSUE TITLE
Should we port the FAQ chapter?

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#44]
PBE1 had an [FAQ chapter](https://github.com/SquareBracketAssociates/PharoByExample-english/tree/master/FAQ).

Should we have a similar chapter in the new book?

**Comment by DamienCassou** [comment]
I would not do it now.

**Comment by dmitrizagidulin** [comment]
@DamienCassou thanks. Closing this issue.
