### ISSUE TITLE
Move Monticello section out of Environment and into own chapter

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#47]
Given how central Monticello (and source control in general) is to the Pharo workflow, and given how many different things we need to cover in the Environment chapter, it would make sense to have a separate `Sharing Code` chapter.

Objections? (cc @Ducasse / @DamienCassou )

**Comment by Ducasse** [comment]
There is already a chapter on MC on deep into pharo. So I would just keep it small and put a ref to the other book and chapter

**Comment by dmitrizagidulin** [comment]
@Ducasse I'm not suggesting expanding the MC content. I'm just pointing out that the MC sections (as well as sections on changesets and filing code in and out) take up a large portion of the Environment chapter. 
So that we end up having a huge super-chapter. Therefore, it might make sense to extract the source control related sections into their own chapter (keeping the overall size the same, just clearer organization).

**Comment by Ducasse** [comment]
Ok for me. What you should see if that if people want to port the translated versions of books the less we change the easier for them.

**Comment by dmitrizagidulin** [comment]
@Ducasse Thanks! I'll go ahead with the Sharing Code chapter, and will definitely keep the translators in mind.

**Comment by dmitrizagidulin** [comment]
Fix committed & merged. Closing.
