### ISSUE TITLE
Travis CI build failing - error with mongodb apt repo

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#55]
Book Travis builds have started failing a day ago or so. 
The error (at least for the latest build: https://travis-ci.org/SquareBracketAssociates/UpdatedPharoByExample/builds/59043465 ) seems to be related to being unable to reach a mongodb repo. (Which brings up the question of, why are we trying to fetch mongodb custom repos for this book? Or is this a standard Travis sources list?)

**Comment by Ducasse** [comment]
I do not understand how mongo is related to this book.

**Comment by dmitrizagidulin** [comment]
Ok, the Travis CI build seems to be passing now. The mongodb repo error seems to have gone away. (I also don't understand how it's related, but I suspect it has to do with the default Travis CI sources list -- they try to make it easy to CI-test commonly used databases).
Closing.
