### ISSUE TITLE
SUnit - remove "executable comment" sentence?

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#57]
SUnit, around [line 280](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/f0b13888e759a6fb0d214699e27b87a270d35697/SUnit/SUnit.pillar#L280-L281):

```
We usually include an executable comment in our test methods that allows us to
run them with a ''do it'' from the browser, as shown below.

[[[caption=Executable comments in test methods
MyExampleSetTest>>>testRemove
	"self run: #testRemove"
	full remove: 5.
	self assert: (full includes: 6).
	self deny: (full includes: 5)
]]]
```

Is this still the case? Given that there are convenient 'run this test' icons next to each test methods, and that we go through like 3 other methods of running an individual test, why is an executable comment still necessary or recommended?

**Comment by Ducasse** [comment]
You can say some people.... because I do it.

**Comment by dmitrizagidulin** [comment]
Thanks :) I changed the phrasing to 'some people'.
