### ISSUE TITLE
Uppercase variable name in Syntax In a Nutshell chapter?

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#6]
The start of the Syntax in a Nutshell chapter (https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/master/SyntaxNutshell/SyntaxNutshell.pillar#L9-L18 ) refers to a `StartDay` day variable:

```
When this is the case it will assign it to the variable ==StartDay==.

[[[language=Smalltalk
startDay: aSymbol

   (DayNames includes: aSymbol)
      ifTrue: [ StartDay := aSymbol ]
      ifFalse: [ self error: aSymbol, ' is not a recognised day name' ]
]]]
```
I wanted to double-check that this is intentional, before correcting. `StartDay` seems like it's an instance variable, and so, shouldn't it be `startDay` instead? (Possibly the same thing for `DayNames`, though I can see how that can refer to a global).

**Comment by DamienCassou** [comment]
@Ducasse Steph ?

**Comment by Ducasse** [comment]
my code is correct in the image we have

startDay: aSymbol

	(DayNames includes: aSymbol)
		ifTrue: [ StartDay := aSymbol ]
		ifFalse: [ self error: aSymbol, ' is not a recognised day name' ]

and StartDay is a class variable

**Comment by dmitrizagidulin** [comment]
@Ducasse thanks!

Oh, speaking of image - is there a repository for the updated corresponding image?
(The old one, http://www.pharobyexample.org/image/PBE-OneClick-1.1.app.zip , is linked off the book website. Is there a similar new one that's being built by CI?)

**Comment by Ducasse** [comment]
Hi 

we will use Pharo 40 
Then for certain examples (in the model chapter I think that we should build an example so that we do not have to change all the time the chapter). And we can publish it on SmalltalkHub

**Comment by dmitrizagidulin** [comment]
Got it, thanks! :)
