### ISSUE TITLE
SUnit - verify that SUnit implementation source code is still the same

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#61]
In the [Implementation of SUnit](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/f0b13888e759a6fb0d214699e27b87a270d35697/SUnit/SUnit.pillar#L660) section, we walk the readers through SUnit source code.
Verify the source code still matches the book in Pharo 4.0.

**Comment by jecisc** [comment]
https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/f0b13888e759a6fb0d214699e27b87a270d35697/SUnit/SUnit.pillar#L753

Miss the last line of the method.

**Comment by jecisc** [comment]
Else all the code match Pharo 4 in the Implementation of SUnit section.

**Comment by jecisc** [comment]
Issue corrected with PR: https://github.com/SquareBracketAssociates/UpdatedPharoByExample/pull/103
