### ISSUE TITLE
BasicClasses - edit the '400 methods in Object' section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#65]
In BasicClasses, around line 23, we say:
```
Astonishingly, there
are some 400 methods to be found here (including extensions). In other words,
every class that you define will automatically provide these 400 methods,
whether you know what they do or not. Note that some of the methods should be
removed and new versions of Pharo may remove some of the superfluous methods.
```
Several things:
1. Verify that the method count is still 400-some in Pharo 4.0
2. In fact, let's give a snippet of code that counts the number of methods in a class
3. Let's cut the last sentence, `Note that some of the methods should be removed and new versions of Pharo may remove some of the superfluous methods.`

**Comment by Ducasse** [comment]
aClass selectors size

**Comment by dmitrizagidulin** [comment]
Thanks!
Fix committed, closing.
