### ISSUE TITLE
Environment - Update 'Senders and implementors of a message' section

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#67]
Refactor the [Senders and implementors of a message](https://github.com/SquareBracketAssociates/UpdatedPharoByExample/blob/7bc09c9045dc6a815f760b92363c262f120fe962/Environment/Environment.pillar#L166) section.

1. Update the shortcuts and right-click menu descriptions to new Pharo
2. ` If you look at the senders of ==drawOn:== in ==AtomMorph>>drawOn:==` - AtomMorph is no longer in the Image. Select another example class, and update the subsequent paragraphs
3. Update the screenshots

**Comment by Ducasse** [comment]
You are doing an incredible work. I spent so much time on this book that this is difficult for me to push and focus on the others. So I really appreciate.

**Comment by dmitrizagidulin** [comment]
@Ducasse - thank you! (By the way, I am also in awe of the work you guys have already done. Just porting the Environment chapter alone, from LaTeX to Pillar, made me realize what colossal amounts of work have already been put into this book).

**Comment by dmitrizagidulin** [comment]
Fix merged. Closing.
