### ISSUE TITLE
PharoObjectModel - add different example to replace 'showColorCube'

### ISSUE THREAD

**Issue by dmitrizagidulin** [SquareBracketAssociates/UpdatedPharoByExample#73]
In the `Class methods` section, remove the code snippet `Color class>>showColorCube`.
Looks like that method is no longer in the image.

(Is there a similar neat invocation that we can substitute, or just snip it?)

**Comment by Ducasse** [comment]
I thought that may be we should build a simple example  and use it as example :)

**Comment by dmitrizagidulin** [comment]
@Ducasse Ok. I'll comment out the mention of `Color class>>showColorCube`, and leave this issue open as a reminder to write a different example.

**Comment by nicolaihess** [comment]
I know use the example method
Color class >> wheel
