### ISSUE TITLE
Some anchors are broken and it would be good to have some conventions

### ISSUE THREAD

**Issue by jecisc** [SquareBracketAssociates/UpdatedPharoByExample#84]
Some anchors are broken, we need change them.
Plus it would be good to have the same type of anchor everywhere (ch:nameOfChapter, mth:nameOfScript, fig:nameOfFig).

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:model'

*** Warning: PRReferenceNotFound: Can't find anchor named 'mth:renderdemo'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:democss'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:dialogs'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:chooseCheese'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:stackMachine'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:ajax-processing'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:cross'

*** Warning: PRReferenceNotFound: Can't find anchor named 'mth:firstDrawOn'

*** Warning: PRReferenceNotFound: Can't find anchor named 'mth:firstContains'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:overdrawBug'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:bug'

*** Warning: PRReferenceNotFound: Can't find anchor named 'mth:mouseDown'

*** Warning: PRReferenceNotFound: Can't find anchor named 'mth:handleKeystroke'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:dialogName'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:popup'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:streams'

*** Warning: PRReferenceNotFound: Can't find anchor named 'fig:collsByImpl'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:basicClasses'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:syntax'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:streams'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:metaclasses'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:env'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:sunit'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:syntax'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:regex'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:collections'

*** Warning: PRReferenceNotFound: Can't find anchor named 'sec:Monticello'

*** Warning: PRReferenceNotFound: Can't find anchor named 'sec:categoriesPackages'

*** Warning: PRReferenceNotFound: Can't find anchor named 'sec:extensions'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:sunit'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:tour'

*** Warning: PRReferenceNotFound: Can't find anchor named 'RestartDetectIfNone.'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:sunit'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:metaclasses'

*** Warning: PRReferenceNotFound: Can't find anchor named 'sec:classVars'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:firstApp'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:syntax'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:basicClasses'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:model'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:basicClasses'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:collections'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:tour'

*** Warning: PRReferenceNotFound: Can't find anchor named ' Shift '

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:tour'

*** Warning: PRReferenceNotFound: Can't find anchor named 'cha:env'

**Comment by jecisc** [comment]
I did a pull request with the corrections. The cha:chapter warning are still here. They'll be delete when the inter-file links will be done in Pillar.

**Comment by DamienCassou** [comment]
CyrilFerlicot <notifications@github.com> writes:

> It would be good to have the same type of anchor everywhere
> (ch:nameOfChapter, mth:nameOfScript, fig:nameOfFig).

I would use "scr" instead of "mth" because we can put many different
things in a script, not just methods.

I would also add "sec" for sections inside chapters.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by dmitrizagidulin** [comment]
@jecisc @DamienCassou Do we have consensus about changing all the `mth:` labels to `scr:`?  If yes, I'm happy to go through and change them. If no, let's close this issue, since it was fixed by Cyril's PR #86.

**Comment by jecisc** [comment]
+1 for `scr:`

**Comment by dmitrizagidulin** [comment]
Sounds good. I can change all the `mth:`.

**Comment by dmitrizagidulin** [comment]
Changes committed, closing.
