### ISSUE TITLE
Figure on Morphic needs immprovement

### ISSUE THREAD

**Issue by jecisc** [SquareBracketAssociates/UpdatedPharoByExample#85]
A lot of figures are missing into the Morphic chapter or need improvement on the size.

**Comment by Ducasse** [comment]
strange because they should be in the svn repository of the original book
I can look for them.

**Comment by jecisc** [comment]
We miss:
grabhandle.png
bug.png
movehandle.png
debughandle.png

**Comment by Ducasse** [comment]
strange it was not in the morphic chapter.

On 17 May 2015, at 15:04, CyrilFerlicot <notifications@github.com> wrote:

> We miss:
> grabhandle.png
> bug.png
> movehandle.png
> debughandle.png
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------------------------
Stéphane Ducasse
http://stephane.ducasse.free.fr
http://www.synectique.eu / http://www.pharo.org 
03 59 35 87 52
Assistant: Julie Jonas 
03 59 57 78 50
03 59 35 86 16

S. Ducasse - Inria
40, avenue Halley, 
Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
Villeneuve d'Ascq 59650
France

**Comment by Ducasse** [comment]
reply found them I will commit them

On 17 May 2015, at 15:04, CyrilFerlicot <notifications@github.com> wrote:

> We miss:
> grabhandle.png
> bug.png
> movehandle.png
> debughandle.png
> 
> —
> Reply to this email directly or view it on GitHub.
> 

--------------------------------------------
Stéphane Ducasse
http://stephane.ducasse.free.fr
http://www.synectique.eu / http://www.pharo.org 
03 59 35 87 52
Assistant: Julie Jonas 
03 59 57 78 50
03 59 35 86 16

S. Ducasse - Inria
40, avenue Halley, 
Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
Villeneuve d'Ascq 59650
France

**Comment by jecisc** [comment]
Thank you !

**Comment by Ducasse** [comment]
in fact I did not find in pbe and sbe 

>> grabhandle.png
>> bug.png
>> 
>> 

On 17 May 2015, at 15:53, Stéphane Ducasse <stephane.ducasse@inria.fr> wrote:

> reply found them I will commit them
> 
> On 17 May 2015, at 15:04, CyrilFerlicot <notifications@github.com> wrote:
> 
>> We miss:
>> grabhandle.png
>> bug.png
>> movehandle.png
>> debughandle.png
>> 
>> —
>> Reply to this email directly or view it on GitHub.
>> 
> 
> --------------------------------------------
> Stéphane Ducasse
> http://stephane.ducasse.free.fr
> http://www.synectique.eu / http://www.pharo.org 
> 03 59 35 87 52
> Assistant: Julie Jonas 
> 03 59 57 78 50
> 03 59 35 86 16
> 
> S. Ducasse - Inria
> 40, avenue Halley, 
> Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
> Villeneuve d'Ascq 59650
> France
> 

--------------------------------------------
Stéphane Ducasse
http://stephane.ducasse.free.fr
http://www.synectique.eu / http://www.pharo.org 
03 59 35 87 52
Assistant: Julie Jonas 
03 59 57 78 50
03 59 35 86 16

S. Ducasse - Inria
40, avenue Halley, 
Parc Scientifique de la Haute Borne, Bât.A, Park Plaza
Villeneuve d'Ascq 59650
France

**Comment by jecisc** [comment]
I begin to work on the Morphic chapter.

**Comment by jecisc** [comment]
StarMorph class doesn't exist anymore. I propose to use BalloonMorph instead.

**Comment by jecisc** [comment]
Should be correct with PR https://github.com/SquareBracketAssociates/UpdatedPharoByExample/pull/100
