### ISSUE TITLE
Broken URL in README.md

### ISSUE THREAD

**Issue by foresterre** [SquareBracketAssociates/UpdatedPharoByExample#89]
The URLs below the chapter progress, pointing to the HTML and PDF chapters of the book are broken.

This is because the URLs either contain a suffix .pillar or a suffix .pier (before the extension (.html, .pdf)). 

The builds on the build server are made without these suffixes.

Example, Chapter 1: preface in the README.md points towards:
https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/Preface/Preface.pillar.html

However, on the build server the file is located at:

https://ci.inria.fr/pharo-contribution/job/UpdatedPharoByExample/lastSuccessfulBuild/artifact/Preface/Preface.html

It is for me unclear whether this was done on purpose, or not. I apologize in advance if it was.

**Comment by jecisc** [comment]
Yes i saw that ! I tried to correct it this week end but I had some trouble then I had to stop.
I'll correct that!
It's because we changed the output extensions in Pillar.

**Comment by jecisc** [comment]
Corrected with https://github.com/SquareBracketAssociates/UpdatedPharoByExample/pull/90

**Comment by foresterre** [comment]
Great! Thank you for corrections.

**Comment by dmitrizagidulin** [comment]
Fix is now merged. Closing.
Thanks again! :)
