### ISSUE TITLE
We could talk about the window group a little.

### ISSUE THREAD

**Issue by jecisc** [SquareBracketAssociates/UpdatedPharoByExample#91]
I discovered the option "create window group", that's really useful when we are on a project with a lot of classes. We could talk a little about that somewhere on the book what do you think ?

**Comment by jecisc** [comment]
https://www.youtube.com/watch?v=GGJZeajjWGU

**Comment by dmitrizagidulin** [comment]
Great idea! We should definitely mention it either in the Environment chapter, or in one of the earlier intro/overview chapters.
+1 from me.

**Comment by jecisc** [comment]
Great :)
